--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Beneficio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Beneficio" (
    "Id" integer NOT NULL,
    nome_beneficio character varying(100) NOT NULL,
    percentual numeric(18,2) NOT NULL
);


ALTER TABLE public."Beneficio" OWNER TO postgres;

--
-- Name: Beneficio_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Beneficio" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Beneficio_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Contribuinte; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Contribuinte" (
    "Id" integer NOT NULL,
    "RazaoSocial" character varying(100) NOT NULL,
    "Cnpj" character varying(14) NOT NULL,
    "DataAbertura" date NOT NULL,
    "RegimeTributacao" integer NOT NULL
);


ALTER TABLE public."Contribuinte" OWNER TO postgres;

--
-- Name: ContribuinteBeneficio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ContribuinteBeneficio" (
    "Id" integer NOT NULL,
    "ContribuinteId" integer NOT NULL,
    "BeneficioId" integer NOT NULL
);


ALTER TABLE public."ContribuinteBeneficio" OWNER TO postgres;

--
-- Name: ContribuinteBeneficio_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ContribuinteBeneficio" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ContribuinteBeneficio_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Contribuinte_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Contribuinte" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contribuinte_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Beneficio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Beneficio" ("Id", nome_beneficio, percentual) FROM stdin;
\.


--
-- Data for Name: Contribuinte; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Contribuinte" ("Id", "RazaoSocial", "Cnpj", "DataAbertura", "RegimeTributacao") FROM stdin;
\.


--
-- Data for Name: ContribuinteBeneficio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ContribuinteBeneficio" ("Id", "ContribuinteId", "BeneficioId") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20241224204840_CriacaoTabelas	9.0.0
\.


--
-- Name: Beneficio_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Beneficio_Id_seq"', 1, true);


--
-- Name: ContribuinteBeneficio_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ContribuinteBeneficio_Id_seq"', 2, true);


--
-- Name: Contribuinte_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Contribuinte_Id_seq"', 1, true);


--
-- Name: Beneficio PK_Beneficio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Beneficio"
    ADD CONSTRAINT "PK_Beneficio" PRIMARY KEY ("Id");


--
-- Name: Contribuinte PK_Contribuinte; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contribuinte"
    ADD CONSTRAINT "PK_Contribuinte" PRIMARY KEY ("Id");


--
-- Name: ContribuinteBeneficio PK_ContribuinteBeneficio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ContribuinteBeneficio"
    ADD CONSTRAINT "PK_ContribuinteBeneficio" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_ContribuinteBeneficio_BeneficioId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ContribuinteBeneficio_BeneficioId" ON public."ContribuinteBeneficio" USING btree ("BeneficioId");


--
-- Name: IX_ContribuinteBeneficio_ContribuinteId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ContribuinteBeneficio_ContribuinteId" ON public."ContribuinteBeneficio" USING btree ("ContribuinteId");


--
-- Name: ContribuinteBeneficio FK_ContribuinteBeneficio_Beneficio_BeneficioId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ContribuinteBeneficio"
    ADD CONSTRAINT "FK_ContribuinteBeneficio_Beneficio_BeneficioId" FOREIGN KEY ("BeneficioId") REFERENCES public."Beneficio"("Id") ON DELETE CASCADE;


--
-- Name: ContribuinteBeneficio FK_ContribuinteBeneficio_Contribuinte_ContribuinteId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ContribuinteBeneficio"
    ADD CONSTRAINT "FK_ContribuinteBeneficio_Contribuinte_ContribuinteId" FOREIGN KEY ("ContribuinteId") REFERENCES public."Contribuinte"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

